# Generated by Django 3.2.11 on 2022-01-15 22:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 15, 22, 56, 23, 458839, tzinfo=utc)),
        ),
    ]
