# Generated by Django 3.2.11 on 2022-01-15 22:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='interval',
            field=models.IntegerField(choices=[(1, '15 minutes'), (2, '30 minutes'), (3, '45 minutes')], default=1),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 15, 22, 56, 23, 458177, tzinfo=utc)),
        ),
    ]
