# Generated by Django 3.2.11 on 2022-01-15 23:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_auto_20220115_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 15, 23, 6, 6, 748397, tzinfo=utc)),
        ),
    ]
