# Generated by Django 3.2.11 on 2022-01-17 00:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_alter_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 17, 0, 25, 56, 292458, tzinfo=utc)),
        ),
    ]
